name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure
        run: mkdir -p build && cd build && cmake ..

      - name: Build
        run: cmake --build build --parallel

      - name: Run tests
        run: cd build && ctest --output-on-failure